# The definition of color schemes.
schemes:
  gruvbox_material_hard_dark: &gruvbox_material_hard_dark
    primary:
      background: '0x1d2021'
      foreground: '0xd4be98'
    normal:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x32302f'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_medium_dark: &gruvbox_material_medium_dark
    primary:
      background: '0x282828'
      foreground: '0xd4be98'
    normal:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x3c3836'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
  gruvbox_material_soft_dark: &gruvbox_material_soft_dark
    primary:
      background: '0x32302f'
      foreground: '0xd4be98'
    normal:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'
    bright:
      black:   '0x45403d'
      red:     '0xea6962'
      green:   '0xa9b665'
      yellow:  '0xd8a657'
      blue:    '0x7daea3'
      magenta: '0xd3869b'
      cyan:    '0x89b482'
      white:   '0xd4be98'

# Apply the color scheme.
colors: *gruvbox_material_medium_dark